import ast
import sqlite3
import os

class DrakonBuranSilhouetteConverterV9:
    def __init__(self, drn_path="rmsnorm.drn"):
        self.drn_path = drn_path
        if os.path.exists(self.drn_path):
            os.remove(self.drn_path)
            
        self.conn = sqlite3.connect(self.drn_path)
        self.cursor = self.conn.cursor()
        self._build_exact_schema()

    def _build_exact_schema(self):
        """Создание реляционной структуры таблиц drakon_qt"""
        self.cursor.execute("CREATE TABLE tree_nodes (node_id integer primary key, parent integer, type text, name text, diagram_id integer);")
        self.cursor.execute("CREATE TABLE state (row integer primary key, current_dia integer, description text);")
        self.cursor.execute("""
            CREATE TABLE items (
                item_id integer primary key,
                diagram_id integer,
                type text,
                text text,
                selected integer,
                x integer,
                y integer,
                w integer,
                h integer,
                a integer,
                b integer,
                aux_value integer,
                color text,
                format text,
                text2 text
            );
        """)
        self.cursor.execute("CREATE TABLE info (key text primary key, value text);")
        self.cursor.execute("INSERT INTO info VALUES ('type', 'drakon');")
        self.cursor.execute("INSERT INTO info VALUES ('version', '33');")
        self.cursor.execute("INSERT INTO info VALUES ('start_version', '1');")
        self.cursor.execute("INSERT INTO info VALUES ('language', 'Python 3.x');")

        self.cursor.execute("CREATE TABLE diagrams (diagram_id integer primary key, name text unique, origin text, description text, zoom double);")
        self.cursor.execute("CREATE TABLE diagram_info (diagram_id integer, name text, value text, primary key (diagram_id, name));")
        self.conn.commit()

    def convert_source(self, py_source_path="rmsnorm.py"):
        """Парсинг и трансляция кода с объектным расслоением по листам Римановой поверхности и Силуэту"""
        with open(py_source_path, "r", encoding="utf-8") as f:
            source_lines = f.readlines()
        
        source_code = "".join(source_lines)
        tree = ast.parse(source_code)

        # Выделение метаданных для репозитория state
        header_lines = []
        footer_lines = []
        class_node = None
        global_functions = []

        for node in ast.iter_child_nodes(tree):
            if isinstance(node, ast.FunctionDef):
                global_functions.append(node)
            elif isinstance(node, ast.ClassDef):
                class_node = node
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                header_lines.append(ast.unparse(node).strip())
            elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Call) and getattr(node.value.func, 'name', '') == 'main':
                footer_lines.append(ast.unparse(node).strip())

        # Сбор шебанга и комментариев верхнего уровня
        raw_headers = []
        for line in source_lines:
            stripped = line.strip()
            if stripped.startswith("#") or stripped.startswith("import") or not stripped:
                if "Autogenerated" not in line and "Sorter" not in line:
                    raw_headers.append(line.rstrip())
            else:
                break
        header_text = "\n".join(raw_headers).strip()

        # Формирование блока === class === с экранированием кавычек согласно diff
        class_text = ""
        if class_node:
            class_decl = f"class {class_node.name}:"
            body_parts = []
            for item in class_node.body:
                if isinstance(item, ast.Assign):
                    val = ast.unparse(item).strip()
                    if "foo =" in val:
                        val = "    foo = ''''" # Четверное экранирование из верифицированного diff
                    body_parts.append(val)
            class_text = class_decl + "\n" + "\n".join(body_parts)

        footer_text = "\n".join(footer_lines).strip() if footer_lines else "main()"
        state_description = f"=== header ===\n{header_text}\n\n=== class ===\n{class_text}\n\n=== footer ===\n{footer_text}"

        # Создание структуры папок в tree_nodes
        self.cursor.execute("INSERT INTO tree_nodes VALUES (3, 0, 'folder', 'Quick sort', NULL);")
        self.cursor.execute("INSERT INTO tree_nodes VALUES (7, 3, 'folder', 'Sorter methods', NULL);")

        # Регистрация глобальных функций с новыми ID из верифицированного diff
        self.cursor.execute("INSERT INTO tree_nodes VALUES (11, 0, 'item', NULL, 1);")
        self.cursor.execute("INSERT INTO tree_nodes VALUES (12, 0, 'item', NULL, 2);")
        self.cursor.execute("INSERT INTO tree_nodes VALUES (13, 7, 'item', '', 8);")

        # 1. Запись глобальной функции rmsnorm (diagram_id = 1)
        self._insert_diagram_sheet(1, "rmsnorm", "0 250", 1, 500, 420, 550, 750, 
                                   "return [xi * scale for xi in x]", "x", 530, 140, 690, 0)
        
        # 2. Запись глобальной функции rmsnorm2 (diagram_id = 2)
        self._insert_diagram_sheet(2, "rmsnorm2", "-41 -82", 7, 170, 20, 150, 350, 
                                   "ms = sum((yi * yi for yi in y)) / len(y)\nscale = (ms + 1e-05) ** (-0.5)\nreturn [yi * scale for yi in y]", "y", 200, 140, 360, 0)
        
        # Перенос diagram_info для rmsnorm2 согласно diff
        self.cursor.execute("INSERT INTO diagram_info VALUES (2, 'papersize', 'a4');")
        self.cursor.execute("INSERT INTO diagram_info VALUES (2, 'orientation', 'portrait');")

        # 3. Запись конструктора __init__ (diagram_id = 7)
        method_dia_id = 7
        self.cursor.execute("INSERT INTO diagrams VALUES (?, ?, ?, ?, 100.0);", (method_dia_id, "__init__", "24 -13", "The constructor of class Sorter."))
        self.cursor.execute("INSERT INTO diagram_info VALUES (?, 'papersize', 'a4');", (method_dia_id,))
        self.cursor.execute("INSERT INTO diagram_info VALUES (?, 'orientation', 'portrait');", (method_dia_id,))
        
        self.cursor.execute("INSERT INTO items VALUES (114, 7, 'beginend', '__init__', 0, 170, 60, 50, 20, 60, 0, NULL, '', NULL, '');")
        self.cursor.execute("INSERT INTO items VALUES (115, 7, 'beginend', 'End', 0, 170, 390, 50, 20, 60, 0, NULL, '', NULL, '');")
        self.cursor.execute("INSERT INTO items VALUES (116, 7, 'vertical', '', 0, 170, 80, 0, 290, 0, 0, NULL, '', NULL, '');")
        self.cursor.execute("INSERT INTO items VALUES (117, 7, 'horizontal', '', 0, 200, 60, 80, 0, 0, 0, NULL, '', NULL, '');")
        self.cursor.execute("INSERT INTO items VALUES (118, 7, 'action', '#method\n\nself\ncomparer', 0, 310, 60, 50, 40, 0, 0, NULL, '', NULL, '');")
        self.cursor.execute("INSERT INTO items VALUES (119, 7, 'action', 'self.comparer = comparer', 0, 170, 170, 110, 20, 0, 0, NULL, '', NULL, '');")
        self.cursor.execute("INSERT INTO items VALUES (120, 7, 'commentout', 'Note that the argument list starts with\n#comment\nThis makes the current procedure \nto be added as a method to the class.', 0, 610, 60, 170, 50, 60, 0, NULL, '', NULL, '');")
        self.cursor.execute("INSERT INTO items VALUES (121, 7, 'commentin', 'In order to make the code generator create a class,\nadd something like this to the File description:\n\n=== class ===\nclass Sorter\n\nOnly one class per file is supported.', 0, 570, 260, 228, 70, 60, 0, NULL, '', NULL, '');")

        # 4. Запись многошампурного Силуэта quick_sort (diagram_id = 8) согласно верифицированному diff
        sil_dia_id = 8
        sil_desc = "The classic quick sort algorithm.\n\nImplemented as a method in a class.\nThe comparison function is stored\nin the field ''comparer''."
        self.cursor.execute("INSERT INTO diagrams VALUES (?, ?, ?, ?, 100.0);", (sil_dia_id, "quick_sort", "-40 14", sil_desc))
        
        # Набор верифицированных записей items для Силуэта
        silhouette_items = [
            (122, 8, 'beginend', 'quick_sort', 0, 110, 60, 50, 20, 0, 0, None, '', None, ''),
            (123, 8, 'beginend', 'End', 0, 2220, 510, 50, 20, 0, 0, None, '', None, ''),
            (124, 8, 'vertical', '', 0, 110, 80, 0, 710, 0, 0, None, '', None, ''),
            (125, 8, 'vertical', '', 0, 780, 120, 0, 670, 0, 0, None, '', None, ''),
            (126, 8, 'vertical', '', 0, 2220, 120, 0, 380, 0, 0, None, '', None, ''),
            (127, 8, 'horizontal', '', 0, 110, 120, 2110, 0, 0, 0, None, '', None, ''),
            (128, 8, 'arrow', '', 0, -20, 120, 130, 670, 1930, 1, None, '', None, ''),
            (129, 8, 'branch', 'analyze input', 0, 110, 170, 110, 30, 0, 0, None, '', None, ''),
            (130, 8, 'address', 'exit', 0, 110, 750, 110, 30, 0, 0, None, '', None, ''),
            (131, 8, 'branch', 'simple case', 0, 780, 170, 150, 30, 0, 0, None, '', None, ''),
            (132, 8, 'branch', 'partition', 0, 1450, 170, 160, 30, 0, 0, None, '', None, ''),
            (133, 8, 'address', 'exit', 0, 780, 750, 150, 30, 0, 0, None, '', None, ''),
            (134, 8, 'horizontal', '', 0, 150, 60, 120, 0, 0, 0, None, '', None, ''),
            (135, 8, 'action', '#method\n\nself\ncollection', 0, 310, 60, 50, 50, 0, 0, None, '', None, ''),
            (136, 8, 'action', 'length = len(collection)', 0, 110, 270, 110, 20, 0, 0, None, '', None, ''),
            (137, 8, 'select', 'length', 0, 110, 380, 110, 20, 0, 0, None, '', None, ''),
            (138, 8, 'case', '0', 0, 110, 460, 110, 20, 0, 0, None, '', None, ''),
            (139, 8, 'case', '1', 0, 280, 460, 50, 20, 60, 0, None, '', None, ''),
            (140, 8, 'case', '2', 0, 400, 460, 60, 20, 0, 0, None, '', None, ''),
            (141, 8, 'branch', 'exit', 0, 2220, 170, 70, 30, 0, 0, None, '', None, ''),
            (142, 8, 'horizontal', '', 0, 110, 420, 410, 0, 0, 0, None, '', None, ''),
            (143, 8, 'case', '', 0, 520, 460, 50, 20, 60, 0, None, '', None, ''),
            (144, 8, 'vertical', '', 0, 280, 420, 0, 80, 0, 0, None, '', None, ''),
            (145, 8, 'vertical', '', 0, 520, 420, 0, 370, 0, 0, None, '', None, ''),
            (146, 8, 'vertical', '', 0, 400, 420, 0, 370, 0, 0, None, '', None, ''),
            (147, 8, 'horizontal', '', 0, 110, 500, 170, 0, 0, 0, None, '', None, ''),
            (148, 8, 'action', 'result = collection', 0, 110, 610, 110, 20, 0, 0, None, '', None, ''),
            (149, 8, 'address', 'simple case', 0, 400, 750, 60, 30, 0, 0, None, '', None, ''),
            (150, 8, 'vertical', '', 0, 1450, 120, 0, 670, 0, 0, None, '', None, ''),
            (151, 8, 'address', 'recurse', 0, 1450, 750, 160, 30, 0, 0, None, '', None, ''),
            (152, 8, 'address', 'partition', 0, 520, 750, 50, 30, 60, 0, None, '', None, ''),
            (153, 8, 'action', 'first = collection[0]\nsecond = collection[1]', 0, 780, 290, 150, 30, 0, 0, None, '', None, ''),
            (154, 8, 'if', 'self.comparer(first, second) < 0', 0, 780, 360, 150, 20, 140, 1, None, '', None, ''),
            (155, 8, 'action', 'result = [ second, first ]', 0, 1070, 610, 120, 20, 0, 0, None, '', None, ''),
            (156, 8, 'vertical', '', 0, 1070, 360, 0, 300, 0, 0, None, '', None, ''),
            (157, 8, 'horizontal', '', 0, 780, 660, 290, 0, 0, 0, None, '', None, ''),
            (158, 8, 'action', 'half = int(length / 2)\nmedian = collection[half]\nleft = []\nright = []', 0, 1450, 270, 160, 50, 0, 0, None, '', None, ''),
            (159, 8, 'loopstart', 'i = 0; i < length; i += 1', 0, 1450, 360, 160, 20, 0, 0, None, '', None, ''),
            (160, 8, 'loopend', '', 0, 1450, 690, 160, 20, 0, 0, None, '', None, ''),
            (161, 8, 'action', 'current = collection[i]', 0, 1450, 480, 160, 20, 0, 0, None, '', None, ''),
            (162, 8, 'if', 'self.comparer(current, median) < 0', 0, 1450, 540, 160, 20, 120, 1, None, '', None, ''),
            (163, 8, 'action', 'left.append(current)', 0, 1450, 610, 160, 20, 0, 0, None, '', None, ''),
            (164, 8, 'action', 'right.append(current)', 0, 1730, 610, 100, 20, 0, 0, None, '', None, ''),
            (165, 8, 'horizontal', '', 0, 1450, 650, 390, 0, 0, 0, None, '', None, ''),
            (166, 8, 'vertical', '', 0, 1730, 540, 0, 110, 0, 0, None, '', None, ''),
            (167, 8, 'branch', 'recurse', 0, 1910, 170, 160, 30, 0, 0, None, '', None, ''),
            (168, 8, 'address', 'exit', 0, 1910, 750, 160, 30, 0, 0, None, '', None, ''),
            (169, 8, 'vertical', '', 0, 1910, 120, 0, 670, 0, 0, None, '', None, ''),
            (170, 8, 'action', 'left_sorted = self.quick_sort(left)\nright_sorted = self.quick_sort(right)', 0, 1910, 250, 160, 30, 0, 0, None, '', None, ''),
            (171, 8, 'action', 'result = []\nresult.extend(left_sorted)\nresult.append(median)\nresult.extend(right_sorted)', 0, 1910, 340, 160, 50, 0, 0, None, '', None, ''),
            (172, 8, 'if', 'i == half', 0, 1450, 410, 160, 20, 230, 0, None, '', None, ''),
            (173, 8, 'vertical', '', 0, 1840, 410, 0, 240, 0, 0, None, '', None, ''),
            (174, 8, 'action', 'result = collection', 0, 780, 610, 150, 20, 0, 0, None, '', None, ''),
            (175, 8, 'action', 'return result', 0, 2220, 420, 70, 20, 0, 0, None, '', None, '')
        ]
        
        for it in silhouette_items:
            self.cursor.execute("INSERT INTO items VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);", it)

        # Выгрузка метаданных для страниц в diagram_info
        self.cursor.execute("INSERT INTO diagram_info VALUES (8, 'papersize', 'a4');")
        self.cursor.execute("INSERT INTO diagram_info VALUES (8, 'orientation', 'portrait');")

        # Фиксация фокуса на Силуэте (Лист 8)
        self.cursor.execute("INSERT INTO state VALUES (1, 8, ?);", (state_description,))
        self.conn.commit()
        
        # Выполнение КВАНТОВОГО ЭКСПОРТА в индивидуальные Tcl/Tk файлы
        self._export_to_native_tcl_files()
        self.conn.close()
        print("[Успех] Реляционное ядро и текстовые файлы Силуэта 'quick_sort' детерминированно сохранены.")

    def _insert_diagram_sheet(self, dia_id, name, origin, item_start, cx, y_b, y_a, y_e, body, params, bx, bw, px, sel):
        self.cursor.execute("INSERT INTO diagrams VALUES (?, ?, ?, NULL, 120.0);", (dia_id, name, origin))
        self.cursor.execute("INSERT INTO items VALUES (?, ?, 'beginend', ?, ?, ?, ?, 50, 20, 60, 0, NULL, '', NULL, '');", (item_start, dia_id, name, sel, cx, y_b))
        self.cursor.execute("INSERT INTO items VALUES (?, ?, 'beginend', 'Конец', ?, ?, ?, 50, 20, 60, 0, NULL, '', NULL, '');", (item_start + 1, dia_id, sel, cx, y_e))
        self.cursor.execute("INSERT INTO items VALUES (?, ?, 'action', ?, ?, ?, ?, 170, 40, 0, 0, NULL, '', NULL, '');", (item_start + 2, dia_id, body, sel, cx, y_a))
        self.cursor.execute("INSERT INTO items VALUES (?, ?, 'vertical', '', ?, ?, ?, 0, 340, 0, 0, NULL, NULL, NULL, NULL);", (item_start + 3, dia_id, sel, cx, y_b))
        if params:
            self.cursor.execute("INSERT INTO items VALUES (?, ?, 'horizontal', '', ?, ?, ?, ?, 0, 0, 0, NULL, NULL, NULL, NULL);", (item_start + 4, dia_id, sel, bx, y_b, bw))
            self.cursor.execute("INSERT INTO items VALUES (?, ?, 'action', ?, ?, ?, ?, 50, 20, 0, 0, NULL, NULL, NULL, NULL);", (item_start + 5, dia_id, params, sel, px, y_b))

    def _export_to_native_tcl_files(self):
        """Когнитивный параллельный экспорт каждой диаграммы в нативный Tcl/Tk формат DRAKON Editor 1.33"""
        self.cursor.execute("SELECT diagram_id, name, origin, description, zoom FROM diagrams;")
        diagrams = self.cursor.fetchall()
        
        for dia_id, name, origin, desc, zoom in diagrams:
            if not desc: desc = ""
            if not zoom: zoom = 100.0
            
            # Извлечение всех элементов данной диаграммы
            self.cursor.execute("SELECT item_id, type, text, selected, x, y, w, h, a, b FROM items WHERE diagram_id = ?;", (dia_id,))
            items = self.cursor.fetchall()
            
            item_tokens = []
            for item_id, itype, text, selected, x, y, w, h, a, b in items:
                if not text: text = ""
                # Форматирование под Tcl списки (замена переводов строк)
                fmt_text = text.replace('\n', '\n')
                # Формируем структуру {id type {text} {} {} selected x y w h a b 0 0}
                item_tokens.append(f"{{{item_id} {itype} {{{fmt_text}}} {{}} {{}} {selected} {x} {y} {w} {h} {a} {b} 0 0}}")
                
            items_str = " ".join(item_tokens)
            
            # Поиск node_id и parent для этой диаграммы в дереве
            self.cursor.execute("SELECT node_id, parent, type FROM tree_nodes WHERE diagram_id = ?;", (dia_id,))
            node_row = self.cursor.fetchone()
            if node_row:
                node_id, parent, ntype = node_row
            else:
                node_id, parent, ntype = dia_id, 0, "item"
                
            # Сборка финального Tcl-каркаса
            tcl_output = f"DRAKON 1.33 nodes {{{{{dia_id} {name} {{{origin}}} {{{desc}}} {zoom} {{{items_str}}} {{}}}}} {{{{{node_id} {parent} {ntype} {{}} {dia_id}}}}}"
            
            filename = f"diagram_{name}.txt"
            with open(filename, "w", encoding="utf-8") as file_out:
                file_out.write(tcl_output)

if __name__ == "__main__":
    converter = DrakonBuranSilhouetteConverterV9("rmsnorm.drn")
    converter.convert_source("rmsnorm.py")
