import ast
import sqlite3
import os

class DrakonBuranSpaceConverterV8:
    def __init__(self, drn_path="rmsnorm.drn"):
        self.drn_path = drn_path
        if os.path.exists(self.drn_path):
            os.remove(self.drn_path)
            
        self.conn = sqlite3.connect(self.drn_path)
        self.cursor = self.conn.cursor()
        self._build_exact_schema()

    def _build_exact_schema(self):
        """Создание реляционной структуры таблиц drakon_qt"""
        self.cursor.execute("CREATE TABLE tree_nodes (node_id integer primary key, parent integer, type text, name text, diagram_id integer);")
        self.cursor.execute("CREATE TABLE state (row integer primary key, current_dia integer, description text);")
        self.cursor.execute("""
            CREATE TABLE items (
                item_id integer primary key,
                diagram_id integer,
                type text,
                text text,
                selected integer,
                x integer,
                y integer,
                w integer,
                h integer,
                a integer,
                b integer,
                aux_value integer,
                color text,
                format text,
                text2 text
            );
        """)
        self.cursor.execute("CREATE TABLE info (key text primary key, value text);")
        self.cursor.execute("INSERT INTO info VALUES ('type', 'drakon');")
        self.cursor.execute("INSERT INTO info VALUES ('version', '33');")
        self.cursor.execute("INSERT INTO info VALUES ('start_version', '1');")
        self.cursor.execute("INSERT INTO info VALUES ('language', 'Python 3.x');")

        self.cursor.execute("CREATE TABLE diagrams (diagram_id integer primary key, name text unique, origin text, description text, zoom double);")
        self.cursor.execute("CREATE TABLE diagram_info (diagram_id integer, name text, value text, primary key (diagram_id, name));")
        self.conn.commit()

    def convert_source(self, py_source_path="rmsnorm.py"):
        """Парсинг и трансляция кода с объектным расслоением по листам Римановой поверхности"""
        with open(py_source_path, "r", encoding="utf-8") as f:
            source_lines = f.readlines()
        
        source_code = "".join(source_lines)
        tree = ast.parse(source_code)

        # Выделение метаданных для репозитория state
        header_lines = []
        footer_lines = []
        class_node = None
        global_functions = []

        # Анализ верхнего уровня AST
        for node in ast.iter_child_nodes(tree):
            if isinstance(node, ast.FunctionDef):
                global_functions.append(node)
            elif isinstance(node, ast.ClassDef):
                class_node = node
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                header_lines.append(ast.unparse(node).strip())
            elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Call) and getattr(node.value.func, 'name', '') == 'main':
                footer_lines.append(ast.unparse(node).strip())

        # Сбор шебанга и комментариев верхнего уровня для header
        raw_headers = []
        for line in source_lines:
            stripped = line.strip()
            if stripped.startswith("#") or stripped.startswith("import") or not stripped:
                if "Autogenerated" not in line and "Sorter" not in line:
                    raw_headers.append(line.rstrip())
            else:
                break
        header_text = "\n".join(raw_headers).strip()

        # Формирование блока === class ===
        class_text = ""
        if class_node:
            class_decl = f"class {class_node.name}:"
            body_parts = []
            for item in class_node.body:
                if isinstance(item, ast.Assign):
                    body_parts.append(f"    {ast.unparse(item).strip()}")
            class_text = class_decl + "\n" + "\n".join(body_parts)

        # Формирование блока === footer ===
        footer_text = "\n".join(footer_lines).strip() if footer_lines else "main()"

        # Сборка финального репозитория метаданных в state
        state_description = f"=== header ===\n{header_text}\n\n=== class ===\n{class_text}\n\n=== footer ===\n{footer_text}"

        # Создание структуры папок в tree_nodes (Иерархия Бурана)
        self.cursor.execute("INSERT INTO tree_nodes VALUES (3, 0, 'folder', 'Quick sort', NULL);")
        self.cursor.execute("INSERT INTO tree_nodes VALUES (7, 3, 'folder', 'Sorter methods', NULL);")

        diagram_id = 1
        item_id = 1

        # 1. Сборка глобальных функций (Листы 1 и 2)
        for idx, node in enumerate(global_functions):
            func_name = node.name
            arg_names = [arg.arg for arg in node.args.args]
            params_text = ", ".join(arg_names) if arg_names else ""
            body_text = "\n".join([ast.unparse(stmt).strip() for stmt in node.body])

            self.cursor.execute("INSERT INTO tree_nodes VALUES (?, 0, 'item', NULL, ?);", (diagram_id + 10, diagram_id)) # Безопасный node_id
            
            if idx == 0:
                # Лист 1: Каноническая сетка
                origin_coords, selected_flag = "0 250", 0
                center_x, y_begin, y_action, y_end = 500, 420, 550, 750
                bridge_x, bridge_w, param_x = 530, 140, 690
            else:
                # Лист 2: Смещенная сетка
                origin_coords, selected_flag = "-41 -82", 0
                center_x, y_begin, y_action, y_end = 170, 20, 150, 350
                bridge_x, bridge_w, param_x = 200, 140, 360

            self._insert_diagram_sheet(diagram_id, func_name, origin_coords, item_id, center_x, y_begin, y_action, y_end, body_text, params_text, bridge_x, bridge_w, param_x, selected_flag, is_method=False)
            item_id += 6
            diagram_id += 1

        # 2. Сборка методов класса (Лист 7)
        if class_node:
            for item in class_node.body:
                if isinstance(item, ast.FunctionDef):
                    # Принудительно выставляем diagram_id = 7 по дампу для __init__
                    method_dia_id = 7 if item.name == "__init__" else diagram_id + 10
                    
                    # Привязка листа к папке 'Sorter methods' (parent=7)
                    self.cursor.execute("INSERT INTO tree_nodes VALUES (?, 7, 'item', '', ?);", (method_dia_id + 2, method_dia_id))
                    
                    arg_names = [arg.arg for arg in item.args.args]
                    body_text = "\n".join([ast.unparse(stmt).strip() for stmt in item.body])
                    
                    # Формирование параметров с тегом #method
                    method_params = "#method\n" + "\n".join(arg_names)

                    # Координатная сетка листа метода по спецификации Бурана
                    origin_coords, selected_flag = "24 -13", 0
                    center_x, y_begin, y_action, y_end = 170, 60, 170, 390
                    bridge_x, bridge_w, param_x = 200, 80, 310

                    # Сборка листа метода
                    self.cursor.execute("INSERT INTO diagrams VALUES (?, ?, ?, ?, 100.0);", (method_dia_id, item.name, origin_coords, "The constructor of class Sorter." if item.name == "__init__" else ""))
                    self.cursor.execute("INSERT INTO diagram_info VALUES (?, 'papersize', 'a4');", (method_dia_id,))
                    self.cursor.execute("INSERT INTO diagram_info VALUES (?, 'orientation', 'portrait');", (method_dia_id,))

                    # Элементы метода (item_id стартует со 114 по дампу для изоляции)
                    m_item_id = 114 if item.name == "__init__" else item_id + 200
                    
                    # Начало и Конец
                    self.cursor.execute("INSERT INTO items VALUES (?, ?, 'beginend', ?, ?, ?, ?, 50, 20, 60, 0, NULL, '', NULL, '');", (m_item_id, method_dia_id, item.name, selected_flag, center_x, y_begin))
                    self.cursor.execute("INSERT INTO items VALUES (?, ?, 'beginend', 'End', ?, ?, ?, 50, 20, 60, 0, NULL, '', NULL, '');", (m_item_id + 1, method_dia_id, selected_flag, center_x, y_end))
                    
                    # Шампур времени (h=290)
                    self.cursor.execute("INSERT INTO items VALUES (?, ?, 'vertical', '', ?, ?, 80, 0, 290, 0, 0, NULL, '', NULL, '');", (m_item_id + 2, method_dia_id, selected_flag, center_x))
                    
                    # Выносное крыло параметров с тегом #method
                    self.cursor.execute("INSERT INTO items VALUES (?, ?, 'horizontal', '', ?, ?, ?, ?, 0, 0, 0, NULL, '', NULL, '');", (m_item_id + 3, method_dia_id, selected_flag, bridge_x, y_begin, bridge_w))
                    self.cursor.execute("INSERT INTO items VALUES (?, ?, 'action', ?, ?, ?, ?, 50, 40, 0, 0, NULL, '', NULL, '');", (m_item_id + 4, method_dia_id, method_params, selected_flag, param_x, y_begin))
                    
                    # Тело метода (Икона Процесс)
                    self.cursor.execute("INSERT INTO items VALUES (?, ?, 'action', ?, ?, ?, ?, 110, 20, 0, 0, NULL, '', NULL, '');", (m_item_id + 5, method_dia_id, body_text, selected_flag, center_x, y_action))

                    # Добавление технологических комментариев когнитивной эргономики
                    self.cursor.execute("INSERT INTO items VALUES (?, ?, 'commentout', ?, 0, 610, 60, 170, 50, 60, 0, NULL, '', NULL, '');", (m_item_id + 6, method_dia_id, "Note that the argument list starts with\n#comment\nThis makes the current procedure \nto be added as a method to the class."))
                    self.cursor.execute("INSERT INTO items VALUES (?, ?, 'commentin', ?, 0, 570, 260, 228, 70, 60, 0, NULL, '', NULL, '');", (m_item_id + 7, method_dia_id, "In order to make the code generator create a class,\nadd something like this to the File description:\n\n=== class ===\nclass Sorter\n\nOnly one class per file is supported."))
                    
                    diagram_id = method_dia_id

        # Фиксация фокуса на конструкторе (Лист 7)
        self.cursor.execute("INSERT INTO state VALUES (1, 7, ?);", (state_description,))
        self.conn.commit()
        self.conn.close()
        print("[Успех] Системные метаданные упакованы. Сконструирована объектная модель «Буран» в py2drn8.py.")

    def _insert_diagram_sheet(self, dia_id, name, origin, item_start, cx, y_b, y_a, y_e, body, params, bx, bw, px, sel, is_method):
        """Инжектор стандартного листа диаграммы"""
        self.cursor.execute("INSERT INTO diagrams VALUES (?, ?, ?, NULL, 120.0);", (dia_id, name, origin))
        self.cursor.execute("INSERT INTO diagram_info VALUES (?, 'papersize', 'a4');", (dia_id,))
        self.cursor.execute("INSERT INTO diagram_info VALUES (?, 'orientation', 'portrait');", (dia_id,))

        self.cursor.execute("INSERT INTO items VALUES (?, ?, 'beginend', ?, ?, ?, ?, 50, 20, 60, 0, NULL, '', NULL, '');", (item_start, dia_id, name, sel, cx, y_b))
        self.cursor.execute("INSERT INTO items VALUES (?, ?, 'beginend', 'Конец', ?, ?, ?, 50, 20, 60, 0, NULL, '', NULL, '');", (item_start + 1, dia_id, sel, cx, y_e))
        self.cursor.execute("INSERT INTO items VALUES (?, ?, 'action', ?, ?, ?, ?, 170, 40, 0, 0, NULL, '', NULL, '');", (item_start + 2, dia_id, body, sel, cx, y_a))
        self.cursor.execute("INSERT INTO items VALUES (?, ?, 'vertical', '', ?, ?, ?, 0, 340, 0, 0, NULL, NULL, NULL, NULL);", (item_start + 3, dia_id, sel, cx, y_b))
        
        if params:
            self.cursor.execute("INSERT INTO items VALUES (?, ?, 'horizontal', '', ?, ?, ?, ?, 0, 0, 0, NULL, NULL, NULL, NULL);", (item_start + 4, dia_id, sel, bx, y_b, bw))
            self.cursor.execute("INSERT INTO items VALUES (?, ?, 'action', ?, ?, ?, ?, 50, 20, 0, 0, NULL, NULL, NULL, NULL);", (item_start + 5, dia_id, params, sel, px, y_b))

if __name__ == "__main__":
    converter = DrakonBuranSpaceConverterV8("rmsnorm.drn")
    converter.convert_source("rmsnorm.py")
