#!/usr/bin/env python
# coding: utf-8

import sys

# Символы Юникод

# Autogenerated with DRAKON Editor 1.33

def rmsnorm(x):
    ms = sum((xi * xi for xi in x)) / len(x)
    scale = (ms + 1e-05) ** (-0.5)
    return [xi * scale for xi in x]


def rmsnorm2(y):
    ms = sum((yi * yi for yi in y)) / len(y)
    scale = (ms + 1e-05) ** (-0.5)
    return [yi * scale for yi in y]

class Sorter:
    foo = ""


    def __init__(self, comparer):
        self.comparer = comparer

main()
